/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderRecord = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'palletType' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Nat),
  'netWeight' : IDL.Int,
  'deliveryDate' : Time,
  'orderType' : IDL.Text,
  'grossWeight' : IDL.Int,
  'deliveryContact' : IDL.Text,
  'timestamp' : Time,
  'materialDescription' : IDL.Text,
  'cutWeight' : IDL.Int,
  'billNo' : IDL.Nat,
  'material' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const OtherServiceRecord = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Int,
  'remarks' : IDL.Text,
});
export const PiercingServiceRecord = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Int,
  'remarks' : IDL.Text,
});
export const RepairOrderRecord = IDL.Record({
  'status' : IDL.Text,
  'assignTo' : IDL.Text,
  'addedMaterialWeight' : IDL.Int,
  'date' : Time,
  'deliveryDate' : Time,
  'totalCost' : IDL.Int,
  'deliveryStatus' : IDL.Text,
  'materialCost' : IDL.Int,
  'material' : IDL.Text,
  'makingCharge' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalNetWeight' : IDL.Nat,
  'totalCutWeight' : IDL.Nat,
  'totalGrossWeight' : IDL.Nat,
});
export const OtherServiceStats = IDL.Record({
  'totalCount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
});
export const PiercingStats = IDL.Record({
  'totalCount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
});
export const RepairOrderStats = IDL.Record({
  'totalMaterialCost' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'totalMakingCharge' : IDL.Nat,
  'totalCost' : IDL.Nat,
});
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'phoneNo' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addOtherService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addPiercingService' : IDL.Func(
      [Time, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRepairOrder' : IDL.Func(
      [
        Time,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getAllOtherServices' : IDL.Func(
      [],
      [IDL.Vec(OtherServiceRecord)],
      ['query'],
    ),
  'getAllPiercingServices' : IDL.Func(
      [],
      [IDL.Vec(PiercingServiceRecord)],
      ['query'],
    ),
  'getAllRepairOrders' : IDL.Func([], [IDL.Vec(RepairOrderRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [OrderRecord], ['query']),
  'getOrderStats' : IDL.Func([], [OrderStats], ['query']),
  'getOtherService' : IDL.Func([IDL.Nat], [OtherServiceRecord], ['query']),
  'getOtherServiceStats' : IDL.Func([], [OtherServiceStats], ['query']),
  'getPiercingService' : IDL.Func(
      [IDL.Nat],
      [PiercingServiceRecord],
      ['query'],
    ),
  'getPiercingStats' : IDL.Func([], [PiercingStats], ['query']),
  'getRecentOrders' : IDL.Func([IDL.Nat], [IDL.Vec(OrderRecord)], ['query']),
  'getRecentOtherServices' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OtherServiceRecord)],
      ['query'],
    ),
  'getRecentPiercingServices' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PiercingServiceRecord)],
      ['query'],
    ),
  'getRecentRepairOrders' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RepairOrderRecord)],
      ['query'],
    ),
  'getRepairOrder' : IDL.Func([IDL.Nat], [RepairOrderRecord], ['query']),
  'getRepairOrderStats' : IDL.Func([], [RepairOrderStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        Time,
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateRepairOrder' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderRecord = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'palletType' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Nat),
    'netWeight' : IDL.Int,
    'deliveryDate' : Time,
    'orderType' : IDL.Text,
    'grossWeight' : IDL.Int,
    'deliveryContact' : IDL.Text,
    'timestamp' : Time,
    'materialDescription' : IDL.Text,
    'cutWeight' : IDL.Int,
    'billNo' : IDL.Nat,
    'material' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const OtherServiceRecord = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Int,
    'remarks' : IDL.Text,
  });
  const PiercingServiceRecord = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Int,
    'remarks' : IDL.Text,
  });
  const RepairOrderRecord = IDL.Record({
    'status' : IDL.Text,
    'assignTo' : IDL.Text,
    'addedMaterialWeight' : IDL.Int,
    'date' : Time,
    'deliveryDate' : Time,
    'totalCost' : IDL.Int,
    'deliveryStatus' : IDL.Text,
    'materialCost' : IDL.Int,
    'material' : IDL.Text,
    'makingCharge' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalNetWeight' : IDL.Nat,
    'totalCutWeight' : IDL.Nat,
    'totalGrossWeight' : IDL.Nat,
  });
  const OtherServiceStats = IDL.Record({
    'totalCount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
  });
  const PiercingStats = IDL.Record({
    'totalCount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
  });
  const RepairOrderStats = IDL.Record({
    'totalMaterialCost' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'totalMakingCharge' : IDL.Nat,
    'totalCost' : IDL.Nat,
  });
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'phoneNo' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addOtherService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addPiercingService' : IDL.Func(
        [Time, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRepairOrder' : IDL.Func(
        [
          Time,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getAllOtherServices' : IDL.Func(
        [],
        [IDL.Vec(OtherServiceRecord)],
        ['query'],
      ),
    'getAllPiercingServices' : IDL.Func(
        [],
        [IDL.Vec(PiercingServiceRecord)],
        ['query'],
      ),
    'getAllRepairOrders' : IDL.Func(
        [],
        [IDL.Vec(RepairOrderRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [OrderRecord], ['query']),
    'getOrderStats' : IDL.Func([], [OrderStats], ['query']),
    'getOtherService' : IDL.Func([IDL.Nat], [OtherServiceRecord], ['query']),
    'getOtherServiceStats' : IDL.Func([], [OtherServiceStats], ['query']),
    'getPiercingService' : IDL.Func(
        [IDL.Nat],
        [PiercingServiceRecord],
        ['query'],
      ),
    'getPiercingStats' : IDL.Func([], [PiercingStats], ['query']),
    'getRecentOrders' : IDL.Func([IDL.Nat], [IDL.Vec(OrderRecord)], ['query']),
    'getRecentOtherServices' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OtherServiceRecord)],
        ['query'],
      ),
    'getRecentPiercingServices' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PiercingServiceRecord)],
        ['query'],
      ),
    'getRecentRepairOrders' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RepairOrderRecord)],
        ['query'],
      ),
    'getRepairOrder' : IDL.Func([IDL.Nat], [RepairOrderRecord], ['query']),
    'getRepairOrderStats' : IDL.Func([], [RepairOrderStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          Time,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateRepairOrder' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };