/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const OrderRecord = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'palletType' : IDL.Text,
  'netWeight' : IDL.Nat,
  'orderType' : IDL.Text,
  'grossWeight' : IDL.Nat,
  'deliveryContact' : IDL.Text,
  'timestamp' : Time,
  'materialDescription' : IDL.Text,
  'cutWeight' : IDL.Nat,
  'billNo' : IDL.Nat,
  'material' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const OrderStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalNetWeight' : IDL.Nat,
  'totalCutWeight' : IDL.Nat,
  'totalGrossWeight' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [OrderRecord], ['query']),
  'getOrderStats' : IDL.Func([], [OrderStats], ['query']),
  'getRecentOrders' : IDL.Func([IDL.Nat], [IDL.Vec(OrderRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const OrderRecord = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'palletType' : IDL.Text,
    'netWeight' : IDL.Nat,
    'orderType' : IDL.Text,
    'grossWeight' : IDL.Nat,
    'deliveryContact' : IDL.Text,
    'timestamp' : Time,
    'materialDescription' : IDL.Text,
    'cutWeight' : IDL.Nat,
    'billNo' : IDL.Nat,
    'material' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const OrderStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalNetWeight' : IDL.Nat,
    'totalCutWeight' : IDL.Nat,
    'totalGrossWeight' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [OrderRecord], ['query']),
    'getOrderStats' : IDL.Func([], [OrderStats], ['query']),
    'getRecentOrders' : IDL.Func([IDL.Nat], [IDL.Vec(OrderRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };